addons: 
  firefox: "49.0"
  chrome: stable
after_success: 
  - bash <(curl -s https://codecov.io/bash)
before_install: 
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver
before_script: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
jdk: 
  - oraclejdk8
language: java
script: 
  - ./gradlew check
  - ./gradlew jacocoTestReport
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - chromedriver
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/