addons: 
  firefox: "49.0"
after_success: 
  - bash <(curl -s https://codecov.io/bash)
before_install: 
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
before_script: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
jdk: 
  - oraclejdk8
language: java
script: 
  - ./gradlew check
  - ./gradlew jacocoTestReport
